default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_rails_development

test:
  <<: *default
  database: twitter_rails_test

production:
  <<: *default
  database: twitter_rails_production
  username: twitter_rails
  password: <%= ENV['TWITTER_RAILS_DATABASE_PASSWORD'] %>
